### ISSUE TITLE
Are you using spider bot to scan Arduino libraries which misused the Wire library?

### ISSUE THREAD

**Issue by KillingJacky** [Koepel/How-to-use-the-Arduino-Wire-library#1]
Just curious

**Comment by Koepel** [comment]
No, I use Github itself to search for it and also Google. The combination requestFrom + while + available + wait is suspicious, but I use other search combinations as well. Even when I don't search for it I see more than enough libraries that use the Wire library in the wrong way.

Let me test this. I just searched with the Github Search for those four words, I select the newest first, Code and C++. Then 4 of the first 5 results use the Wire library in the wrong way.
